// KERNI Telegram Bot Configuration
// This file is for local development only
// For production, this file is generated by GitHub Actions with real secrets

window.TELEGRAM_CONFIG = {
  botToken: 'YOUR_BOT_TOKEN_HERE',
  chatId: '-1002578873461'
};

console.log('Local config.js loaded:', window.TELEGRAM_CONFIG);

// Для тестирования замените на реальные значения:
// botToken: '5555666677:AAHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz'
// chatId: '-1001234567890'

// Примеры:
// botToken: '5555666677:AAHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz'
// chatId: '-1001234567890' (для групп/каналов)
// chatId: '123456789' (для личных чатов) 