// KERNI Telegram Bot Configuration
// This file is for local development only
// For production, this file is generated by GitHub Actions with real secrets

window.TELEGRAM_CONFIG = {
  botToken: '7687712916:AAHYrMQ2bYqAaWNydGuW6dqjhK1CjawJIyE',
  chatId: '-1002578873461'
};

console.log('Local config.js loaded:', window.TELEGRAM_CONFIG);