name: Deploy KERNI to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Debug secrets
      run: |
        echo "Checking if secrets are available..."
        if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
          echo "TELEGRAM_BOT_TOKEN is set (length: ${#TELEGRAM_BOT_TOKEN})"
        else
          echo "TELEGRAM_BOT_TOKEN is NOT set"
        fi
        if [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
          echo "TELEGRAM_CHAT_ID is set (value: ${{ secrets.TELEGRAM_CHAT_ID }})"
        else
          echo "TELEGRAM_CHAT_ID is NOT set"
        fi
    
    - name: Create Telegram config
      run: |
        cat > config.js << EOF
        // KERNI Telegram Bot Configuration
        window.TELEGRAM_CONFIG = {
          botToken: '${{ secrets.TELEGRAM_BOT_TOKEN }}',
          chatId: '${{ secrets.TELEGRAM_CHAT_ID }}'
        };
        EOF
        echo "Config file created:"
        cat config.js
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true 